title: Your Awesome Blog
description: A place where I share my thoughts on technology, life, and everything in between
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # your site's URL

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate: 6
paginate_path: "/page/:num/"

# Author information
author:
  name: Your Name
  bio: A brief bio about yourself
  email: your.email@example.com
  twitter_username: yourtwitterhandle
  github_username: yourgithubhandle
  linkedin_username: yourlinkedinhandle

# Plugin settings
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-search

# Comments
disqus:
  shortname: your-disqus-shortname

# Google Analytics
google_analytics: UA-XXXXXXXX-X 